/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

const url='postgresql://main_owner:Z8uYmOhfNB3E@ep-plain-voice-a58f8v1s.us-east-2.aws.neon.tech/main?sslmode=require'